services:
  - type: web
    name: gradify-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "your-app-name.onrender.com"
      - key: GEMINI_API_KEY
        sync: false 