# Generated by Django 5.2.3 on 2025-06-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
